pool:
  vmImage: 'windows-latest'

steps:
# - task: Gradle@3
#   inputs:
#     gradleWrapperFile: 
#     tasks: 'build'
#     publishJUnitResults: true
#     testResultsFiles: '**/TEST-*.xml'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     gradleOptions: '-Xmx3072m'
#     sonarQubeRunAnalysis: false
#     spotBugsAnalysis: false
#   displayName: gradlew assembleDebug test
#   timeoutInMinutes: 5
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts